# Setup
title:               Long Nguyen's Blog
tagline:             'Long Nguyen'
description:         'Long Nguyen'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Long Nguyen
  url:               https://longn.me
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
